In [1]:
import pandas as pd
import numpy as np

DATA_DIR = '../data/Finance_raw/'
START_DATE = '2006-01-01'

# 발표 시차(publication lag) 보정 — 데이터 누수 방지
# 월별 거시지표: 기준월의 약 1~2개월 뒤 발표 → 2개월 뒤로 이동 (보수적)
# 주별 EIA 보고서: 주 마감 후 다음 주 수요일경 발표 → 1주 뒤로 이동
MONTHLY_LAG = pd.DateOffset(months=2)
WEEKLY_LAG = pd.DateOffset(weeks=1)

## 1. 일별 데이터 로드 (FRED)

In [2]:
# OilPrice (일별)
oilprice = pd.read_csv(DATA_DIR + 'FRED_OilPrice.csv', parse_dates=['observation_date'])
oilprice = oilprice.rename(columns={'observation_date': 'date', 'DCOILWTICO': 'OilPrice'})
oilprice = oilprice[oilprice['date'] >= START_DATE][['date', 'OilPrice']].copy().reset_index(drop=True)
print('OilPrice:', oilprice.shape, oilprice['date'].min(), '~', oilprice['date'].max())

OilPrice: (5271, 2) 2006-01-02 00:00:00 ~ 2026-03-16 00:00:00

In [3]:
# DollarIndex (일별)
dollarindex = pd.read_csv(DATA_DIR + 'FRED_DollarIndex.csv', parse_dates=['observation_date'])
dollarindex = dollarindex.rename(columns={'observation_date': 'date', 'DTWEXBGS': 'DollarIndex'})
dollarindex = dollarindex[dollarindex['date'] >= START_DATE][['date', 'DollarIndex']].copy().reset_index(drop=True)
print('DollarIndex:', dollarindex.shape, dollarindex['date'].min(), '~', dollarindex['date'].max())

DollarIndex: (5270, 2) 2006-01-02 00:00:00 ~ 2026-03-13 00:00:00

In [4]:
# VIX (일별)
vix = pd.read_csv(DATA_DIR + 'FRED_VIX.csv', parse_dates=['observation_date'])
vix = vix.rename(columns={'observation_date': 'date', 'VIXCLS': 'VIX'})
vix = vix[vix['date'] >= START_DATE][['date', 'VIX']].copy().reset_index(drop=True)
print('VIX:', vix.shape, vix['date'].min(), '~', vix['date'].max())

VIX: (5273, 2) 2006-01-02 00:00:00 ~ 2026-03-18 00:00:00

In [5]:
# TermSpread (일별)
termspread = pd.read_csv(DATA_DIR + 'FRED_TermSpread.csv', parse_dates=['observation_date'])
termspread = termspread.rename(columns={'observation_date': 'date', 'T10Y2Y': 'TermSpread'})
termspread = termspread[termspread['date'] >= START_DATE][['date', 'TermSpread']].copy().reset_index(drop=True)
print('TermSpread:', termspread.shape, termspread['date'].min(), '~', termspread['date'].max())

TermSpread: (5273, 2) 2006-01-02 00:00:00 ~ 2026-03-18 00:00:00

In [6]:
# TreasuryYield (일별)
treasuryyield = pd.read_csv(DATA_DIR + 'FRED_TreasuryYield.csv', parse_dates=['observation_date'])
treasuryyield = treasuryyield.rename(columns={'observation_date': 'date', 'DGS10': 'TreasuryYield'})
treasuryyield = treasuryyield[treasuryyield['date'] >= START_DATE][['date', 'TreasuryYield']].copy().reset_index(drop=True)
print('TreasuryYield:', treasuryyield.shape, treasuryyield['date'].min(), '~', treasuryyield['date'].max())

TreasuryYield: (5272, 2) 2006-01-02 00:00:00 ~ 2026-03-17 00:00:00

## 2. 월별 데이터 로드 (FRED)

> 발표 시차 보정: 월별 지표는 기준월 이후에 발표되므로 `date`를 2개월 뒤로 이동 (`MONTHLY_LAG`)

In [7]:
# RealInterestRate (월별)
realinterestrate = pd.read_csv(DATA_DIR + 'FRED_RealInterestRate_month.csv', parse_dates=['observation_date'])
realinterestrate = realinterestrate.rename(columns={'observation_date': 'date', 'REAINTRATREARAT10Y': 'RealInterestRate'})
realinterestrate['date'] = realinterestrate['date'] + MONTHLY_LAG  # 발표 시차 보정
realinterestrate = realinterestrate[realinterestrate['date'] >= START_DATE][['date', 'RealInterestRate']].copy().reset_index(drop=True)
print('RealInterestRate:', realinterestrate.shape, realinterestrate['date'].min(), '~', realinterestrate['date'].max())

RealInterestRate: (245, 2) 2006-01-01 00:00:00 ~ 2026-05-01 00:00:00

In [8]:
# CPI (월별)
cpi = pd.read_csv(DATA_DIR + 'FRED_CPI_month.csv', parse_dates=['observation_date'])
cpi = cpi.rename(columns={'observation_date': 'date', 'CPIAUCSL': 'CPI'})
cpi['date'] = cpi['date'] + MONTHLY_LAG  # 발표 시차 보정
cpi = cpi[cpi['date'] >= START_DATE][['date', 'CPI']].copy().reset_index(drop=True)
print('CPI:', cpi.shape, cpi['date'].min(), '~', cpi['date'].max())

CPI: (244, 2) 2006-01-01 00:00:00 ~ 2026-04-01 00:00:00

In [9]:
# IndustryProduction (월별)
industryproduction = pd.read_csv(DATA_DIR + 'FRED_IndustryProduction_month.csv', parse_dates=['observation_date'])
industryproduction = industryproduction.rename(columns={'observation_date': 'date', 'INDPRO': 'IndustryProduction'})
industryproduction['date'] = industryproduction['date'] + MONTHLY_LAG  # 발표 시차 보정
industryproduction = industryproduction[industryproduction['date'] >= START_DATE][['date', 'IndustryProduction']].copy().reset_index(drop=True)
print('IndustryProduction:', industryproduction.shape, industryproduction['date'].min(), '~', industryproduction['date'].max())

IndustryProduction: (244, 2) 2006-01-01 00:00:00 ~ 2026-04-01 00:00:00

In [10]:
# CPE (월별) - FRED_CPE_month.csv
cpe = pd.read_csv(DATA_DIR + 'FRED_CPE_month.csv', parse_dates=['observation_date'])
cpe = cpe.rename(columns={'observation_date': 'date', 'PCEC96': 'CPE'})
cpe['date'] = cpe['date'] + MONTHLY_LAG  # 발표 시차 보정
cpe = cpe[cpe['date'] >= START_DATE][['date', 'CPE']].copy().reset_index(drop=True)
print('CPE:', cpe.shape, cpe['date'].min(), '~', cpe['date'].max())

CPE: (229, 2) 2007-03-01 00:00:00 ~ 2026-03-01 00:00:00

In [11]:
# FedFundsRate (월별)
fedfundsrate = pd.read_csv(DATA_DIR + 'FRED_FedFundsRate.csv', parse_dates=['observation_date'])
fedfundsrate = fedfundsrate.rename(columns={'observation_date': 'date', 'FEDFUNDS': 'FedFundsRate'})
fedfundsrate['date'] = fedfundsrate['date'] + MONTHLY_LAG  # 발표 시차 보정
fedfundsrate = fedfundsrate[fedfundsrate['date'] >= START_DATE][['date', 'FedFundsRate']].copy().reset_index(drop=True)
print('FedFundsRate:', fedfundsrate.shape, fedfundsrate['date'].min(), '~', fedfundsrate['date'].max())

FedFundsRate: (244, 2) 2006-01-01 00:00:00 ~ 2026-04-01 00:00:00

## 3. 주별 데이터 로드 (EIA)

> 발표 시차 보정: 주별 EIA 보고서는 주 마감 후 발표되므로 `date`를 1주 뒤로 이동 (`WEEKLY_LAG`)

In [12]:
# OilInventories (주별) - 상위 4행 메타데이터 + 1행 헤더 스킵
oilinventories = pd.read_csv(DATA_DIR + 'eia_OilInventories_week.csv', skiprows=5, names=['date', 'OilInventories'])
oilinventories['date'] = pd.to_datetime(oilinventories['date'], format='%m/%d/%Y')
oilinventories['date'] = oilinventories['date'] + WEEKLY_LAG  # 발표 시차 보정
oilinventories['OilInventories'] = pd.to_numeric(oilinventories['OilInventories'], errors='coerce')
oilinventories = oilinventories[oilinventories['date'] >= START_DATE][['date', 'OilInventories']].copy().reset_index(drop=True)
print('OilInventories:', oilinventories.shape, oilinventories['date'].min(), '~', oilinventories['date'].max())

OilInventories: (1055, 2) 2006-01-06 00:00:00 ~ 2026-03-20 00:00:00

In [13]:
# OilProduction (주별) - 상위 4행 메타데이터 + 1행 헤더 스킵
oilproduction = pd.read_csv(DATA_DIR + 'eia_OilProduction_week.csv', skiprows=5, names=['date', 'OilProduction'])
oilproduction['date'] = pd.to_datetime(oilproduction['date'], format='%m/%d/%Y')
oilproduction['date'] = oilproduction['date'] + WEEKLY_LAG  # 발표 시차 보정
oilproduction['OilProduction'] = pd.to_numeric(oilproduction['OilProduction'], errors='coerce')
oilproduction = oilproduction[oilproduction['date'] >= START_DATE][['date', 'OilProduction']].copy().reset_index(drop=True)
print('OilProduction:', oilproduction.shape, oilproduction['date'].min(), '~', oilproduction['date'].max())

OilProduction: (1055, 2) 2006-01-06 00:00:00 ~ 2026-03-20 00:00:00

## 4. OPEC 생산량 월별 데이터 로드 (EIA, wide format)

> 발표 시차 보정: 월별이므로 `date`를 2개월 뒤로 이동 (`MONTHLY_LAG`)

In [14]:
# OPECProduction (월별) - wide format
# INTL.53-1-XXX-TBPD.M: 국가별 'Total petroleum and other liquids' 행 합산
opec_raw = pd.read_csv(DATA_DIR + 'eia_OPECProduction_month.csv', header=1)

total_rows = opec_raw[opec_raw['API'].str.startswith('INTL.53-1-', na=False)]
date_cols = [c for c in opec_raw.columns if c not in ['API', 'Unnamed: 1']]

opec_sum = total_rows[date_cols].apply(pd.to_numeric, errors='coerce').sum(axis=0)
opec_total = opec_sum.reset_index()
opec_total.columns = ['month_str', 'OPECProduction']
opec_total['date'] = pd.to_datetime(opec_total['month_str'], format='%b %Y')
opec_total['date'] = opec_total['date'] + MONTHLY_LAG  # 발표 시차 보정
opec_total = opec_total[opec_total['date'] >= START_DATE][['date', 'OPECProduction']].copy().reset_index(drop=True)

# 합산 결과 0인 행 → 데이터 없음으로 처리
opec_total.loc[opec_total['OPECProduction'] == 0, 'OPECProduction'] = np.nan

print('OPECProduction:', opec_total.shape, opec_total['date'].min(), '~', opec_total['date'].max())
opec_total.head()

OPECProduction: (241, 2) 2006-01-01 00:00:00 ~ 2026-01-01 00:00:00

        date  OPECProduction
0 2006-01-01       33416.949
1 2006-02-01       33407.655
2 2006-03-01       33237.829
3 2006-04-01       33662.727
4 2006-05-01       33628.642

## 5. 외부 조인(Outer Join)으로 병합
- 일별 데이터: 해당 날짜에만 값 존재
- 월별/주별 데이터: 해당 날짜에만 값 존재, 나머지는 NaN

In [15]:
dfs = [
    oilprice,
    realinterestrate,
    cpi,
    dollarindex,
    vix,
    industryproduction,
    cpe,
    oilinventories,
    opec_total,
    oilproduction,
    termspread,
    treasuryyield,
    fedfundsrate,
]

merged = dfs[0]
for df in dfs[1:]:
    merged = pd.merge(merged, df, on='date', how='outer')

merged = merged.sort_values('date').reset_index(drop=True)

# 발표 시차 보정으로 월별/주별 데이터가 일별(OilPrice) 범위 밖으로 밀려나므로 잘라냄
# (그대로 두면 다운스트림 ffill 이 빈 OilPrice 를 가짜 값으로 채움)
merged = merged[merged['date'] <= oilprice['date'].max()].reset_index(drop=True)

# 컬럼 순서 지정
col_order = [
    'date', 'OilPrice', 'RealInterestRate', 'CPI', 'DollarIndex', 'VIX',
    'IndustryProduction', 'CPE', 'OilInventories', 'OPECProduction',
    'OilProduction', 'TermSpread', 'TreasuryYield', 'FedFundsRate'
]
merged = merged[col_order]

print('Merged shape:', merged.shape)
print('Date range:', merged['date'].min(), '~', merged['date'].max())
print()
print('결측치 현황:')
print(merged.isnull().sum())
merged.head(10)

Merged shape: (5342, 14)
Date range: 2006-01-01 00:00:00 ~ 2026-03-16 00:00:00

결측치 현황:
date                     0
OilPrice               273
RealInterestRate      5099
CPI                   5100
DollarIndex            280
VIX                    232
IndustryProduction    5099
CPE                   5113
OilInventories        4288
OPECProduction        5101
OilProduction         4288
TermSpread             289
TreasuryYield          289
FedFundsRate          5099
dtype: int64

,date,OilPrice,RealInterestRate,CPI,DollarIndex,VIX,IndustryProduction,CPE,OilInventories,OPECProduction,OilProduction,TermSpread,TreasuryYield,FedFundsRate
0,2006-01-01,NaN,2.075689,198.1,NaN,NaN,97.5414,NaN,NaN,33416.949,NaN,NaN,NaN,4.0
1,2006-01-02,NaN,NaN,NaN,101.4155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006-01-03,63.11,NaN,NaN,100.7558,11.14,NaN,NaN,NaN,NaN,NaN,0.03,4.37,NaN
3,2006-01-04,63.41,NaN,NaN,100.2288,11.37,NaN,NaN,NaN,NaN,NaN,0.05,4.36,NaN
4,2006-01-05,62.81,NaN,NaN,100.2992,11.31,NaN,NaN,NaN,NaN,NaN,0.04,4.36,NaN
5,2006-01-06,64.21,NaN,NaN,100.0241,11.00,NaN,NaN,305527.0,NaN,4864.0,0.02,4.38,NaN
6,2006-01-09,63.56,NaN,NaN,100.1794,11.13,NaN,NaN,NaN,NaN,NaN,0.02,4.38,NaN
7,2006-01-10,63.41,NaN,NaN,100.1436,10.86,NaN,NaN,NaN,NaN,NaN,0.02,4.43,NaN
8,2006-01-11,63.91,NaN,NaN,99.8710,10.94,NaN,NaN,NaN,NaN,NaN,0.02,4.46,NaN
9,2006-01-12,63.96,NaN,NaN,100.0643,11.20,NaN,NaN,NaN,NaN,NaN,0.03,4.42,NaN

## 6. 저장

In [16]:
output_path = '../data/Finance_Final/F_merged.csv'
merged.to_csv(output_path, index=False)
print(f'저장 완료: {output_path}')
print(f'Shape: {merged.shape}')
merged.tail()

저장 완료: ../data/Finance_Final/F_merged.csv
Shape: (5342, 14)

,date,OilPrice,RealInterestRate,CPI,DollarIndex,VIX,IndustryProduction,CPE,OilInventories,OPECProduction,OilProduction,TermSpread,TreasuryYield,FedFundsRate
5337,2026-03-10,83.71,NaN,NaN,118.7255,24.93,NaN,NaN,NaN,NaN,NaN,0.58,4.15,NaN
5338,2026-03-11,86.80,NaN,NaN,119.2885,24.23,NaN,NaN,NaN,NaN,NaN,0.57,4.21,NaN
5339,2026-03-12,95.61,NaN,NaN,119.8227,27.29,NaN,NaN,NaN,NaN,NaN,0.51,4.27,NaN
5340,2026-03-13,98.48,NaN,NaN,120.5518,27.19,NaN,NaN,443103.0,NaN,13678.0,0.55,4.28,NaN
5341,2026-03-16,93.39,NaN,NaN,NaN,23.51,NaN,NaN,NaN,NaN,NaN,0.55,4.23,NaN